#BSUB -J FASTQ2BAM_UL_WGS
#BSUB -W 6:00
#BSUB -M 96G
#BSUB -n 12
#BSUB -R rusage[mem=96G]
#BSUB -u bnsugg@mdanderson.org
#BSUB -cwd /rsrch3/home/lym_myl_rsch/bnsugg/lpWGS_pipeline
#BSUB -q medium
#BSUB -o /rsrch3/home/lym_myl_rsch/bnsugg/lpWGS_pipeline
#BSUB -e /rsrch3/home/lym_myl_rsch/bnsugg/lpWGS_pipeline
module load samtools/1.10
module load bwa/0.7.17
module load fastqc
sh "/rsrch3/home/lym_myl_rsch/bnsugg/lpWGS_pipeline/scripts/lpWGS_pipeline.sh"